=== iamcrowd/metamodel-api-OWL2import/src/main/resources/schemas/eerSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.eer",
  "title": "EER JSON",
  "description": "This JSON represents the information represented by a model described in EER modeling language",
  "type": "object",
  "properties": {
    "entities": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "attributes": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type",
          "datatype"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "datatype": {
            "type": "string"
          }
        }
      }
    },
    "relationships": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "links": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "attribute",
              "isa",
              "relationship"
            ]
          }
        },
        "if": {
          "properties": {
            "type": {
              "const": "attribute"
            }
          }
        },
        "then": {
          "properties": {
            "entity": {
              "type": "string"
            },
            "attribute": {
              "type": "string"
            }
          },
          "required": [
            "entity",
            "attribute"
          ]
        },
        "else": {
          "if": {
            "properties": {
              "type": {
                "const": "isa"
              }
            }
          },
          "then": {
            "properties": {
              "parent": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "constraint": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "exclusive",
                    "overlapping",
                    "union"
                  ]
                }
              }
            },
            "required": [
              "parent",
              "entities",
              "constraint"
            ]
          },
          "else": {
            "if": {
              "properties": {
                "type": {
                  "const": "relationship"
                }
              }
            },
            "then": {
              "properties": {
                "entities": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "cardinality": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "pattern": "([0-9]+|N|\\*)\\.\\.([0-9]+|N|M|\\*)"
                  }
                },
                "roles": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "entities",
                "cardinality",
                "roles"
              ]
            }
          }
        }
      }
    }
  },
  "required": [
    "entities",
    "links"
  ]
}

=== iamcrowd/metamodel-api-OWL2import/src/main/resources/jsonExamples/eerExample.json
{
  "entities": [
    {
      "name": "Person",
      "id": "c51",
      "timestamp": "",
      "position": {
        "x": 580,
        "y": 260
      }
    },
    {
      "name": "Dog",
      "id": "c63",
      "timestamp": "",
      "position": {
        "x": 1020,
        "y": 230
      }
    },
    {
      "name": "Golden",
      "id": "c87",
      "timestamp": "",
      "position": {
        "x": 976,
        "y": 473
      }
    },
    {
      "name": "Pointer",
      "id": "c99",
      "timestamp": "",
      "position": {
        "x": 1140,
        "y": 480
      }
    },
    {
      "name": "Toy",
      "id": "c111",
      "timestamp": "",
      "position": {
        "x": 980,
        "y": 700
      }
    }
  ],
  "attributes": [
    {
      "name": "Name",
      "type": "normal",
      "datatype": "String",
      "id": "c63",
      "timestamp": "",
      "position": {
        "x": 550,
        "y": 310
      }
    },
    {
      "name": "Name",
      "type": "normal",
      "datatype": "Integer",
      "id": "c63",
      "timestamp": "",
      "position": {
        "x": 550,
        "y": 310
      }
    },
    {
      "name": "Age",
      "type": "normal",
      "datatype": "Integer",
      "id": "c63",
      "timestamp": "",
      "position": {
        "x": 550,
        "y": 310
      }
    },
    {
      "name": "Size",
      "type": "normal",
      "datatype": "String",
      "id": "c63",
      "timestamp": "",
      "position": {
        "x": 550,
        "y": 310
      }
    }
  ],
  "relationships": [
    {
      "name": "owns",
      "id": "c75",
      "timestamp": "",
      "position": {
        "x": 780,
        "y": 230
      }
    },
    {
      "name": "has",
      "id": "c228",
      "timestamp": "",
      "position": {
        "x": 990,
        "y": 580
      }
    }
  ],
  "links": [
    {
      "name": "c123",
      "parent": "Dog",
      "entities": [
        "Pointer",
        "Golden"
      ],
      "type": "isa",
      "constraint": [
        "union",
        "exclusive"
      ]
    },
    {
      "name": "owns",
      "id": "c75",
      "entities": [
        "Person",
        "Dog"
      ],
      "cardinality": [
        "0..1",
        "1..1"
      ],
      "roles": [
        "person",
        "dog"
      ],
      "type": "relationship"
    },
    {
      "name": "has",
      "id": "c228",
      "entities": [
        "Golden",
        "Toy"
      ],
      "cardinality": [
        "1..*",
        "1..1"
      ],
      "roles": [
        "golden",
        "toy"
      ],
      "type": "relationship"
    },
    {
      "name": "c76",
      "entity": "Person",
      "attribute": "Name",
      "type": "attribute"
    },
    {
      "name": "c76",
      "entity": "Dog",
      "attribute": "Name",
      "type": "attribute"
    },
    {
      "name": "c76",
      "entity": "Dog",
      "attribute": "Age",
      "type": "attribute"
    },
    {
      "name": "c76",
      "entity": "Dog",
      "attribute": "Size",
      "type": "attribute"
    }
  ]
}
