=== iamcrowd/metamodel-api-OWL2import/src/main/resources/schemas/ormSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.orm",
  "title": "ORM JSON",
  "description": "This JSON represents the information represented by a model described in ORM modeling language",
  "type": "object",
  "properties": {
    "entities": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "connectors": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "parent": {
            "type": "string"
          },
          "entities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string"
          },
          "subtypingContraint": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "relationships": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "entities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "uniquenessConstraints": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "([0-9]+|N|\\*)\\.\\.([0-9]+|N|M|\\*)"
            }
          },
          "mandatory": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string"
          }
        }
      }
    },
    "attributes": {
      "description": "",
      "type": "array"
    },
    "inheritances": {
      "description": "",
      "type": "array"
    }
  },
  "required": [
    "entities",
    "attributes",
    "relationships",
    "inheritances",
    "connectors"
  ]
}

=== iamcrowd/metamodel-api-OWL2import/src/main/resources/jsonExamples/ormExample.json
{
  "entities": [
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Person",
      "ref": "",
      "id": 60,
      "type": "entity",
      "position": {
        "x": 190,
        "y": 190
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Dog",
      "ref": "",
      "id": 74,
      "type": "entity",
      "position": {
        "x": 565,
        "y": 175
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Golden",
      "ref": "",
      "id": 188,
      "type": "entity",
      "position": {
        "x": 430,
        "y": 399.5
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Pointer",
      "ref": "",
      "id": 202,
      "type": "entity",
      "position": {
        "x": 654,
        "y": 399.5
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Toy",
      "ref": "",
      "id": 220,
      "type": "entity",
      "position": {
        "x": 434,
        "y": 642.5
      }
    }
  ],
  "relationships": [
    {
      "name": "http://crowd.fi.uncoma.edu.ar#owns",
      "inverseReading": false,
      "entities": [
        "http://crowd.fi.uncoma.edu.ar#Person",
        "http://crowd.fi.uncoma.edu.ar#Dog"
      ],
      "uniquenessConstraints": [
        "0..1",
        "1..1"
      ],
      "mandatory": [
        "http://crowd.fi.uncoma.edu.ar#Dog"
      ],
      "type": "binaryFactType",
      "position": {
        "x": 380,
        "y": 195
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#has",
      "inverseReading": false,
      "entities": [
        "http://crowd.fi.uncoma.edu.ar#Golden",
        "http://crowd.fi.uncoma.edu.ar#Toy"
      ],
      "uniquenessConstraints": [
        "1..*",
        "1..1"
      ],
      "mandatory": [
        "http://crowd.fi.uncoma.edu.ar#Golden",
        "http://crowd.fi.uncoma.edu.ar#Toy"
      ],
      "type": "binaryFactType",
      "position": {
        "x": 460,
        "y": 515
      }
    }
  ],
  "attributes": [],
  "inheritances": [],
  "connectors": [
    {
      "name": "http://crowd.fi.uncoma.edu.ar#S1",
      "parent": "http://crowd.fi.uncoma.edu.ar#Dog",
      "entities": [
        "http://crowd.fi.uncoma.edu.ar#Golden",
        "http://crowd.fi.uncoma.edu.ar#Pointer"
      ],
      "type": "subtyping",
      "subtypingContraint": ["exclusive","union"],
      "position": {
        "x": 587.5,
        "y": 320.5
      }
    }
  ]
}
